### ISSUE TITLE
F# getPrimes doesn't produce prime numbers.

### ISSUE THREAD

**Issue by spirit11** [patternmatch/functional-programming-in-serverless-world#1]
There is a mistake in getPrimes implementation, ```k``` and ```n``` variables are mixed up:

https://github.com/patternmatch/functional-programming-in-serverless-world/blob/ebad3dbe9ef0700ca739c4ada64c09e647b4a925/aws/dotnet/fsharp/Handlers.fs#L16-L34

This function doesn't produce prime numbers and works considerably faster than it should be, 1.5 times approximately. Execution time benchmark results are probably affected by this issue.

Correct implimentation is like this:

```fsharp
let getPrimes n =
    let sieve = new BitArray((n / 2) + 1, true)
    let result = new ResizeArray<int>(n / 10)
    let upper = int (sqrt (float n))

    if n > 1 then result.Add(2)

    let mutable m = 1

    while 2 * m + 1 <= n do
     if sieve.[m] then
       let k = 2 * m + 1
       if k <= upper then
         let mutable i = m
         while 2 * i < n do sieve.[i] <- false; i <- i + k
       result.Add k
     m <- m + 1

    result
```

**Comment by afronski** [comment]
Yes, indeed - my bad - I will fix that in a separate _PR_. Thank you! :bowing_man: 

One note regarding execution time: it was not so crucial in a sense _which language is faster _but negatively affected the overall cost of the solution (as we are billed based on execution time).
